from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 613)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 841, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.d_tab = QtWidgets.QWidget()
        self.d_tab.setObjectName("d_tab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.d_tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 791, 531))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textEdit_2 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit_3 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout.addWidget(self.textEdit_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.encode_button_d = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.encode_button_d.setObjectName("encode_button_d")
        self.verticalLayout_2.addWidget(self.encode_button_d)
        self.decode_button_d = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.decode_button_d.setObjectName("decode_button_d")
        self.verticalLayout_2.addWidget(self.decode_button_d)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.textBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.d_tab, "")
        self.file_tab = QtWidgets.QWidget()
        self.file_tab.setObjectName("file_tab")
        self.comboBox_2 = QtWidgets.QComboBox(self.file_tab)
        self.comboBox_2.setGeometry(QtCore.QRect(280, 140, 208, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(self.file_tab)
        self.lineEdit.setGeometry(QtCore.QRect(150, 30, 621, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.file_tab)
        self.pushButton.setGeometry(QtCore.QRect(10, 30, 121, 23))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.file_tab)
        self.textEdit.setGeometry(QtCore.QRect(10, 130, 231, 271))
        self.textEdit.setObjectName("textEdit")
        self.encode_button_d_2 = QtWidgets.QPushButton(self.file_tab)
        self.encode_button_d_2.setGeometry(QtCore.QRect(280, 230, 208, 23))
        self.encode_button_d_2.setObjectName("encode_button_d_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.file_tab)
        self.textBrowser_2.setGeometry(QtCore.QRect(530, 120, 231, 311))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.decode_button_d_2 = QtWidgets.QPushButton(self.file_tab)
        self.decode_button_d_2.setGeometry(QtCore.QRect(280, 310, 208, 23))
        self.decode_button_d_2.setObjectName("decode_button_d_2")
        self.decode_button_d_3 = QtWidgets.QPushButton(self.file_tab)
        self.decode_button_d_3.setGeometry(QtCore.QRect(310, 410, 141, 23))
        self.decode_button_d_3.setObjectName("decode_button_d_3")
        self.label_4 = QtWidgets.QLabel(self.file_tab)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 181, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.file_tab)
        self.label_5.setGeometry(QtCore.QRect(540, 90, 72, 15))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.file_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "此处输入字符串"))
        self.label.setText(_translate("MainWindow", "此处输入key，注意格式"))
        self.comboBox.setItemText(0, _translate("MainWindow", "XOR(异或加密解密)"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Caecar(凯撒加密解密)"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Playfair(皮菲特加密解密)"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Hill(希尔加密解密)"))
        self.encode_button_d.setText(_translate("MainWindow", "点击加密"))
        self.decode_button_d.setText(_translate("MainWindow", "点击解密"))
        self.label_3.setText(_translate("MainWindow", "此处显示结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.d_tab), _translate("MainWindow", "直接加密解密"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "XOR(异或加密解密)"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Caecar(凯撒加密解密)"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Playfair(皮菲特加密解密)"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Hill(希尔加密解密)"))
        self.pushButton.setText(_translate("MainWindow", "选择文件"))
        self.encode_button_d_2.setText(_translate("MainWindow", "点击加密"))
        self.decode_button_d_2.setText(_translate("MainWindow", "点击解密"))
        self.decode_button_d_3.setText(_translate("MainWindow", "输出加密文件"))
        self.label_4.setText(_translate("MainWindow", "此处输入key，注意格式"))
        self.label_5.setText(_translate("MainWindow", "密文预览"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.file_tab), _translate("MainWindow", "文件加密解密(暂时仅支持txt文件)"))
        self.menu.setTitle(_translate("MainWindow", "使用说明"))
        self.menu_2.setTitle(_translate("MainWindow", "关于"))
